language: r
cache: packages
after_success:
  - Rscript -e 'library(covr); codecov()'
matrix:
  include:
    - os: linux
      r: oldrel
      r_build_args: --resave-data
      dist: xenial
      warnings_are_errors: true
      sudo: required
      fortran: false
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install libglu1-mesa-dev
        - export DISPLAY=:99.0
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("rgl")'
        - R -e 'install.packages("metadynminer")'
        - R -e 'install.packages("misc3d")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
      env:
        - RGL_USE_NULL=TRUE
    - os: linux
      r: release
      r_build_args: --resave-data
      dist: xenial
      warnings_are_errors: true
      sudo: required
      fortran: false
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install libglu1-mesa-dev
        - export DISPLAY=:99.0
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("rgl")'
        - R -e 'install.packages("metadynminer")'
        - R -e 'install.packages("misc3d")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
      env:
        - RGL_USE_NULL=TRUE
    - os: linux
      r: devel
      r_build_args: --resave-data
      dist: xenial
      warnings_are_errors: true
      sudo: required
      fortran: false
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install libglu1-mesa-dev
        - export DISPLAY=:99.0
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("rgl")'
        - R -e 'install.packages("metadynminer")'
        - R -e 'install.packages("misc3d")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
      env:
        - RGL_USE_NULL=TRUE
    - os: osx
      r: oldrel
      r_build_args: --resave-data
      dist: xenial
      warnings_are_errors: true
      sudo: required
      fortran: false
      osx_image: xcode11.3
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install libglu1-mesa-dev
        - export DISPLAY=:99.0
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("rgl")'
        - R -e 'install.packages("metadynminer")'
        - R -e 'install.packages("misc3d")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
      env:
        - RGL_USE_NULL=TRUE
    - os: osx
      r: release
      r_build_args: --resave-data
      dist: xenial
      warnings_are_errors: true
      sudo: required
      fortran: false
      osx_image: xcode11.3
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install libglu1-mesa-dev
        - export DISPLAY=:99.0
      install:
        - R -e 'install.packages("Rcpp")'
        - R -e 'install.packages("rgl")'
        - R -e 'install.packages("metadynminer")'
        - R -e 'install.packages("misc3d")'
        - R -e 'install.packages("covr")'
        - R -e 'install.packages("testthat")'
      env:
        - RGL_USE_NULL=TRUE

