// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hills3d1
NumericVector hills3d1(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d1(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p1
NumericVector hills3d1p1(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d1p1(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p1(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p2
NumericVector hills3d1p2(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d1p2(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p2(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p3
NumericVector hills3d1p3(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d1p3(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p3(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p12
NumericVector hills3d1p12(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d1p12(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p12(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p13
NumericVector hills3d1p13(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d1p13(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p13(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p23
NumericVector hills3d1p23(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d1p23(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p23(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d1p123
NumericVector hills3d1p123(NumericVector cv1, NumericVector cv2, NumericVector cv3, double width1, double width2, double width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d1p123(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< double >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< double >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< double >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d1p123(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2
NumericVector hills3d2(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d2(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p1
NumericVector hills3d2p1(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d2p1(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p1(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p2
NumericVector hills3d2p2(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d2p2(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p2(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p3
NumericVector hills3d2p3(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d2p3(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p3(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p12
NumericVector hills3d2p12(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d2p12(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p12(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p13
NumericVector hills3d2p13(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d2p13(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p13(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p23
NumericVector hills3d2p23(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d2p23(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p23(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// hills3d2p123
NumericVector hills3d2p123(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, int n, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_hills3d2p123(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP nSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(hills3d2p123(cv1, cv2, cv3, width1, width2, width3, heights, n, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3d
NumericVector fe3d(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_fe3d(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe3d(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp1
NumericVector fe3dp1(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p1, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_fe3dp1(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP p1SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe3dp1(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p1, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp2
NumericVector fe3dp2(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p2, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_fe3dp2(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP p2SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe3dp2(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p2, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp3
NumericVector fe3dp3(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p3, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_fe3dp3(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP p3SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p3(p3SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe3dp3(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p3, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp12
NumericVector fe3dp12(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p1, double p2, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_fe3dp12(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe3dp12(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p1, p2, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp13
NumericVector fe3dp13(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p1, double p3, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_fe3dp13(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP p1SEXP, SEXP p3SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p3(p3SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe3dp13(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p1, p3, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp23
NumericVector fe3dp23(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p2, double p3, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_fe3dp23(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP p2SEXP, SEXP p3SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type p3(p3SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe3dp23(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p2, p3, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}
// fe3dp123
NumericVector fe3dp123(NumericVector cv1, NumericVector cv2, NumericVector cv3, NumericVector width1, NumericVector width2, NumericVector width3, NumericVector heights, double x, double y, double z, double p1, double p2, double p3, int tmin, int tmax);
RcppExport SEXP _metadynminer3d_fe3dp123(SEXP cv1SEXP, SEXP cv2SEXP, SEXP cv3SEXP, SEXP width1SEXP, SEXP width2SEXP, SEXP width3SEXP, SEXP heightsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP p3SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cv1(cv1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv2(cv2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cv3(cv3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width1(width1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width2(width2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type width3(width3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heights(heightsSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type p3(p3SEXP);
    Rcpp::traits::input_parameter< int >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fe3dp123(cv1, cv2, cv3, width1, width2, width3, heights, x, y, z, p1, p2, p3, tmin, tmax));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_metadynminer3d_hills3d1", (DL_FUNC) &_metadynminer3d_hills3d1, 10},
    {"_metadynminer3d_hills3d1p1", (DL_FUNC) &_metadynminer3d_hills3d1p1, 10},
    {"_metadynminer3d_hills3d1p2", (DL_FUNC) &_metadynminer3d_hills3d1p2, 10},
    {"_metadynminer3d_hills3d1p3", (DL_FUNC) &_metadynminer3d_hills3d1p3, 10},
    {"_metadynminer3d_hills3d1p12", (DL_FUNC) &_metadynminer3d_hills3d1p12, 10},
    {"_metadynminer3d_hills3d1p13", (DL_FUNC) &_metadynminer3d_hills3d1p13, 10},
    {"_metadynminer3d_hills3d1p23", (DL_FUNC) &_metadynminer3d_hills3d1p23, 10},
    {"_metadynminer3d_hills3d1p123", (DL_FUNC) &_metadynminer3d_hills3d1p123, 10},
    {"_metadynminer3d_hills3d2", (DL_FUNC) &_metadynminer3d_hills3d2, 10},
    {"_metadynminer3d_hills3d2p1", (DL_FUNC) &_metadynminer3d_hills3d2p1, 10},
    {"_metadynminer3d_hills3d2p2", (DL_FUNC) &_metadynminer3d_hills3d2p2, 10},
    {"_metadynminer3d_hills3d2p3", (DL_FUNC) &_metadynminer3d_hills3d2p3, 10},
    {"_metadynminer3d_hills3d2p12", (DL_FUNC) &_metadynminer3d_hills3d2p12, 10},
    {"_metadynminer3d_hills3d2p13", (DL_FUNC) &_metadynminer3d_hills3d2p13, 10},
    {"_metadynminer3d_hills3d2p23", (DL_FUNC) &_metadynminer3d_hills3d2p23, 10},
    {"_metadynminer3d_hills3d2p123", (DL_FUNC) &_metadynminer3d_hills3d2p123, 10},
    {"_metadynminer3d_fe3d", (DL_FUNC) &_metadynminer3d_fe3d, 12},
    {"_metadynminer3d_fe3dp1", (DL_FUNC) &_metadynminer3d_fe3dp1, 13},
    {"_metadynminer3d_fe3dp2", (DL_FUNC) &_metadynminer3d_fe3dp2, 13},
    {"_metadynminer3d_fe3dp3", (DL_FUNC) &_metadynminer3d_fe3dp3, 13},
    {"_metadynminer3d_fe3dp12", (DL_FUNC) &_metadynminer3d_fe3dp12, 14},
    {"_metadynminer3d_fe3dp13", (DL_FUNC) &_metadynminer3d_fe3dp13, 14},
    {"_metadynminer3d_fe3dp23", (DL_FUNC) &_metadynminer3d_fe3dp23, 14},
    {"_metadynminer3d_fe3dp123", (DL_FUNC) &_metadynminer3d_fe3dp123, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_metadynminer3d(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
